-- tblCComment 데이터

insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 276, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 283, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 293, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 254, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 258, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 272, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 254, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 281, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 263, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 269, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 293, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 292, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 273, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 271, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 250, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 271, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 264, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 293, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 287, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 282, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 255, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 269, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 259, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 257, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 274, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 253, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 279, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 253, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 275, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 281, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 295, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 275, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 252, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 252, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 265, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 272, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 259, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 294, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 268, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 290, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 254, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 268, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 276, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 254, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 279, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 285, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 275, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 292, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 264, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 285, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 276, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 295, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 252, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 280, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 279, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 256, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 271, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 275, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 278, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 265, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 292, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 277, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 279, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 269, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 258, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 272, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 286, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 282, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 290, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 285, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 263, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 296, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 290, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 286, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 261, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 265, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 265, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 253, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 278, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 259, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 293, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 255, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 250, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 280, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 254, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 294, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 294, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 285, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 289, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 291, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 254, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 256, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 281, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 253, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 284, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 280, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 255, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 260, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 296, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 282, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 274, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 286, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 270, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 287, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 261, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 284, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 291, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 252, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 265, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 284, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 261, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 262, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 291, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 253, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 293, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 285, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 253, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 274, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 284, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 251, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 277, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 273, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 278, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 279, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 256, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 254, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 272, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 283, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 265, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 286, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 273, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 264, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 277, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 288, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 284, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 273, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 282, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 274, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 294, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 269, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 271, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 288, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 296, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 279, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 286, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 296, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 280, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 257, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 288, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 266, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 264, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 286, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 265, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 258, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 291, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 274, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 277, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 286, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 260, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 250, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 272, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 266, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 253, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 275, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 296, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 278, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 280, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 290, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 290, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 274, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 252, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 263, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 281, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 294, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 261, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 271, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 252, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 269, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 276, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 251, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 253, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 258, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 276, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 286, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 273, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 271, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 255, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 291, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 263, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 271, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 291, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 251, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 265, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 264, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 265, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 283, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 287, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 287, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 291, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 271, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 273, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 260, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 269, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 250, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 296, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 280, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 272, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 255, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 261, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 268, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 275, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 273, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 286, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 268, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 266, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 259, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 268, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 295, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 253, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 276, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 269, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 266, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 257, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 269, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 285, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 260, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 296, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 276, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 292, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 257, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 259, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 279, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 284, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 264, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 255, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 288, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 256, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 267, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 294, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 271, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 253, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 292, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 262, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 251, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 267, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 279, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 268, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 288, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 291, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 263, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 292, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 295, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 250, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 272, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 284, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 289, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 259, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 273, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 283, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 282, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 252, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 286, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 286, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 281, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 268, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 283, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 276, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 294, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 260, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 254, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 257, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 274, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 290, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 258, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 275, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 268, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 254, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 296, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 269, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 285, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 289, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 251, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 251, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 281, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 273, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 287, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 291, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 289, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 288, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 254, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 291, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 283, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 280, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 263, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 280, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 250, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 286, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 266, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 287, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 256, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 272, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 45, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 179, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 179, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 190, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 18, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 286, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 120, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 167, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 18, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 19, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 221, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 101, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 254, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 86, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 244, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 256, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 146, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 149, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 282, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 127, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 34, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 207, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 265, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 160, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 25, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 116, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 200, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 22, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 114, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 276, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 269, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 235, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 166, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 259, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 275, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 252, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 35, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 199, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 189, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 169, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 155, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 178, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 5, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 285, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 201, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 25, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 115, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 286, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 178, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 269, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 227, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 274, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 75, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 132, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 54, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 243, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 196, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 73, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 104, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 223, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 143, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 48, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 244, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 155, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 238, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 167, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 129, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 126, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 18, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 234, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 238, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 44, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 223, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 46, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 86, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 286, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 143, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 101, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 95, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 149, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 263, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 17, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 136, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 5, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 99, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 130, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 13, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 136, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 203, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 286, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 154, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 117, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 32, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 99, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 215, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 256, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 109, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 183, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 81, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 200, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 296, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 259, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 134, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 93, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 48, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 230, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 172, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 260, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 213, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 60, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 177, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 181, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 207, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 226, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 209, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 20, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 121, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 22, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 275, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 219, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 221, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 2, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 169, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 85, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 99, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 127, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 278, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 7, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 245, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 91, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 282, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 135, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 106, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 61, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 23, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 268, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 178, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 220, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 157, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 84, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 83, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 281, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 64, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 9, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 36, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 121, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 283, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 7, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 236, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 252, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 230, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 33, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 135, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 21, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 154, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 142, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 67, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 242, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 13, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 286, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 262, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 8, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 213, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 202, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 33, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 196, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 88, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 257, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 138, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 229, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 91, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 127, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 204, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 89, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 80, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 146, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 196, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 150, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 78, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 105, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 279, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 171, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 191, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 56, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 202, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 24, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 35, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 152, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 293, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 207, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 22, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 206, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 278, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 166, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 14, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 254, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 149, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 39, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 132, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 185, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 45, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 294, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 234, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 240, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 112, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 188, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 166, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 130, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 127, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 216, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 217, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 199, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 295, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 167, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 202, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 123, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 201, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 51, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 263, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 157, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 66, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 251, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 127, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 20, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 256, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 59, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 177, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 66, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 145, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 266, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 179, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 108, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 8, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 285, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 240, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 124, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 255, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 288, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 117, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 147, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 19, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 90, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 185, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 241, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 35, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 285, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 90, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 243, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 165, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 23, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 57, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 161, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 73, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 122, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 138, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 203, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 68, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 168, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 205, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 222, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 223, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 280, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 238, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 238, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 12, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 115, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 97, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 68, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 7, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 38, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 10, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 95, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 51, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 27, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 149, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 95, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 264, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 231, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 260, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 42, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 295, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 42, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 137, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 263, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 276, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 248, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 117, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 76, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 221, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 19, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 188, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 294, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 270, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 142, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 133, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 238, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 131, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 295, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 288, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 76, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 281, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 293, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 75, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 257, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 193, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 217, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 109, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 37, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 41, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 225, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 194, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 75, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 88, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 228, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 38, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 219, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 113, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 267, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 44, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 281, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 253, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 186, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 37, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 135, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 101, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 164, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 205, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 21, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 4, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 11, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 122, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 134, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 296, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 267, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 102, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 289, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 277, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 142, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 98, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 238, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 142, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 192, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 124, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 62, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 184, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 5, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 167, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 262, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 127, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 188, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 62, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 7, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 219, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 24, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 63, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 145, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 133, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 263, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 254, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 269, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 232, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 50, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 197, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 13, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 25, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 116, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 193, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 124, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 276, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 176, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 79, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 134, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 37, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 293, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 2, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 170, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 253, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 288, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 21, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 153, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 174, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 93, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 266, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 81, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 59, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 209, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 235, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 77, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 108, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 100, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 267, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 38, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 119, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 4, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 105, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 237, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 19, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 38, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 81, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 159, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 228, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 76, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 176, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 171, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 34, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 16, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 57, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 230, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 18, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 296, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 20, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 214, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 150, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 218, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 198, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 39, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 254, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 97, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 70, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 272, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 37, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 131, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 101, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 260, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 137, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 140, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 172, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 244, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 270, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 272, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 146, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 93, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 57, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 169, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 13, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 255, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 108, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 207, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 195, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 284, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 16, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 260, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 116, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 193, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 292, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 265, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 206, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 265, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 229, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 155, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 63, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 176, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 166, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 235, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 120, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 8, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 220, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 186, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 161, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 218, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 210, '네 반갑습니다^^~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 39, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 205, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 88, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 290, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 227, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 246, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user4', 18, '방가방가요!!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 43, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 106, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user11', 271, '사진이 좋네요~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 35, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 259, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 178, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 128, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 113, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 176, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 218, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 164, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 133, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 68, '반갑습니다^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user', 260, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user3', 82, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 11, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user8', 241, '안녕하세요~~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 174, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 69, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user7', 43, '안녕하삼요~', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user1', 223, 'ㅎㅎㅎㅎ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 285, '내용이 참 좋네요^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'farmer', 138, 'ㅋㅋㅋㅋ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 279, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user2', 134, '날씨가 더우니 건강 유의 하세요!', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user6', 243, '행복하시길 바랍니다', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user10', 58, '아.....', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 75, '저는 농부가 되고싶어요ㅠㅠ', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user5', 291, '좋은 글 잘 읽고 갑니다~~^^', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 64, '날씨 진짜 덥네요 후아...', default);
insert into tblCComment (seq, id, postSeq, detail, regdate) values (seqCCom.NextVal, 'user9', 41, '행복하시길 바랍니다', default);

commit;