------------삭제순서--------------------------
---------sequence drop 필수..!--------------
drop sequence seqExp;
drop sequence seqExpApply;
drop sequence seqExpReview;
delete from tblExpReview;
delete from tblExpApply;
delete from tblExp;

-------------------추가 순서------------------
----------------------- tblExp DummyData-------------------------
create sequence seqExp;
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer2','경상남도 거제시 거제중앙로 1274','월촌마을','기타체험','팽이치기','2021-09-21','2021-12-22',default,'010-9822-0909','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',35,default,'03.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer5','강원도 정선군 남면 광락로 354','장구마을','기타체험','물놀이','2021-08-11','2021-10-17',default,'011-9980-1234','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',30,default,'10.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer2','경상남도 거제시 거제중앙로 1274','도래미마을','놀이체험','수박체험','2021-09-01','2021-12-22',default,'010-2231-2245','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',65,default,'07.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer1','강원도 평창군 미탄면 마하길 41-5','알프스마을','전통음식체험','연날리기','2021-09-27','2021-11-15',default,'010-1231-5672','http://www.푸르미농촌체험농장.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',65,default,'08.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer6',' 충청남도 청양군 정산면 천장호길 223-35','도래미마을','놀이체험','딸기체험','2021-09-27','2021-12-02',default,'051-1234-2222','http://www.푸르미농촌체험농장.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',40,default,'10.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer1','경기도 양평군 용문면 청용길 13-6','모꼬지마을','기타체험','나무공예','2021-08-14','2021-10-08',default,'011-9980-1234','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',25,default,'06.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer4','강원도 정선군 남면 광락로 354','고들배기마을','생태체험','동굴탐험','2021-09-21','2021-11-15',default,'010-4532-9554','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',45,default,'');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer2','전라북도 남원시 인월면 인월서길 42','녹향마을','농사체험','양목장체험','2021-09-06','2021-10-07',default,'010-1231-5672','http://www.푸르미농촌체험농장.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',65,default,'');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer4','전라남도 곡성군 고달면 가정마을길 65','도래미마을','전통문화체험','표고버섯 수확','2021-09-06','2021-12-16',default,'010-9822-0909','www.cehum.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',50,default,'10.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer1',' 충청남도 청양군 정산면 천장호길 223-35','개랭이마을','기타체험','물놀이','2021-08-21','2021-10-17',default,'051-1234-2222','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',70,default,'05.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer4','전라남도 담양군 대덕면 무월길 42','가정마을','놀이체험','난타체험','2021-09-06','2021-12-02',default,'010-4532-9554','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',40,default,'04.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer4','전라남도 담양군 대덕면 무월길 42','해바라기마을','전통음식체험','갯벌생태체험','2021-08-01','2021-10-07',default,'010-1231-5672','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',70,default,'07.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer7','강원도 정선군 남면 광락로 354','개미들마을','전통음식체험','수박체험','2021-08-01','2021-11-07',default,'010-1234-5678','https://www.alimi.or.kr/home/a/selectOnestopHome.do','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',45,default,'01.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer7','전라남도 여수시 돌산읍 향일암로 913','해바라기마을','농사체험','쑥개떡 만들기','2021-08-01','2021-12-22',default,'051-1234-2222','https://www.cheonan.go.kr/tour.do','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',30,default,'02.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer1','경기도 양평군 용문면 청용길 13-6','알프스마을','전통문화체험','양목장체험','2021-08-21','2021-11-26',default,'051-1234-2222','www.cehum.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',50,default,'08.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer4','전라남도 여수시 돌산읍 향일암로 913','장구마을','생태체험','고구마캐기','2021-08-14','2021-10-09',default,'010-9899-2123','https://www.alimi.or.kr/home/a/selectOnestopHome.do','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',15,default,'07.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer3','전라북도 남원시 인월면 인월서길 42','갓고을마을','전통음식체험','감자캐기','2021-09-27','2021-10-08',default,'010-9822-0909','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',55,default,'09.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer5','전라북도 남원시 인월면 인월서길 42','산수유마을','전통음식체험','동굴탐험','2021-08-21','2021-12-22',default,'010-4532-9554','http://www.푸르미농촌체험농장.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',20,default,'04.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer2','경상남도 거제시 거제중앙로 1274','갓고을마을','기타체험','갯벌생태체험','2021-09-01','2021-10-09',default,'010-1231-5672','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',40,default,'03.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer6','전라남도 여수시 돌산읍 향일암로 913','산수유마을','기타체험','물놀이','2021-09-01','2021-10-17',default,'010-4532-9554','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',40,default,'08.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer6','전라북도 남원시 인월면 인월서길 42','개랭이마을','놀이체험','떡메치기','2021-09-27','2021-12-22',default,'010-9822-0909','www.cehum.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',20,default,'05.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer1','충청남도 청양군 정산면 천장호길 223-35','장독대마을','전통문화체험','예절학습','2021-09-01','2021-10-07',default,'010-1231-5672','https://www.alimi.or.kr/home/a/selectOnestopHome.do','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',20,default,'02.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer3','경상남도 거제시 거제중앙로 1274','알프스마을','생태체험','팽이치기','2021-09-27','2021-12-22',default,'011-9980-1234','https://www.cheonan.go.kr/tour.do','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',50,default,'10.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer1','충청남도 서천군 마서면 합전길 77','알프스마을','농사체험','자연생태체험','2021-09-13','2021-11-15',default,'010-1234-5678','http://www.푸르미농촌체험농장.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',50,default,'10.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer3','전라북도 남원시 인월면 인월서길 42','도래미마을','농사체험','갯벌생태체험','2021-08-21','2021-11-26',default,'011-9980-1234','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',40,default,'08.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer1','전라남도 곡성군 고달면 가정마을길 65','해바라기마을','만들기체험','농산물수확','2021-08-14','2021-10-17',default,'010-2231-2245','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',45,default,'05.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer1','충청남도 청양군 정산면 천장호길 223-35','산수유마을','전통음식체험','물놀이','2021-08-01','2021-10-27',default,'011-9980-1234','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',65,default,'10.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer4','전라북도 남원시 인월면 인월서길 42','모꼬지마을','생태체험','조롱박공예','2021-08-01','2021-11-26',default,'011-9980-1234','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',15,default,'11.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer2','충청남도 청양군 정산면 천장호길 223-35','장독대마을','생태체험','다도체험','2021-08-11','2021-10-17',default,'010-1234-5678','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',60,default,'07.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer2','충청남도 청양군 정산면 천장호길 223-35','달오름마을','전통문화체험','숭어잡기','2021-08-01','2021-10-07',default,'051-1234-2222','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',35,default,'08.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer',' 충청남도 청양군 정산면 천장호길 223-35','갓고을마을','생태체험','연날리기','2021-08-01','2021-10-07',default,'010-4532-9554','https://www.alimi.or.kr/home/a/selectOnestopHome.do','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',20,default,'07.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer4','강원도 평창군 미탄면 마하길 41-5','달오름마을','농사체험','고구마캐기','2021-09-01','2021-11-07',default,'010-4532-9554','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',65,default,'08.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer3','전라북도 남원시 인월면 인월서길 42','장독대마을','전통음식체험','동굴탐험','2021-09-21','2021-12-02',default,'010-1234-5678','www.cehum.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',20,default,'07.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer4','전라남도 여수시 돌산읍 향일암로 913','알프스마을','놀이체험','기체조','2021-08-01','2021-11-07',default,'010-4532-9554','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',50,default,'01.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer1','강원도 평창군 미탄면 마하길 41-5','알프스마을','전통음식체험','감자캐기','2021-09-27','2021-12-16',default,'051-1234-2222','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',65,default,'04.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer','전라북도 남원시 인월면 인월서길 42','알프스마을','전통음식체험','다도체험','2021-09-01','2021-11-26',default,'010-9899-2123','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',65,default,'08.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer7','전라남도 곡성군 고달면 가정마을길 65','모꼬지마을','전통음식체험','물놀이','2021-08-01','2021-10-09',default,'011-9980-1234','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',50,default,'03.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer4','전라남도 담양군 대덕면 무월길 42','갓고을마을','만들기체험','메기잡기','2021-09-21','2021-11-07',default,'010-1231-5672','http://www.푸르미농촌체험농장.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',70,default,'09.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer2','전라남도 여수시 돌산읍 향일암로 913','알프스마을','바다체험','메기잡기','2021-09-21','2021-10-17',default,'010-9822-0909','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',50,default,'11.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer4','경상남도 거제시 거제중앙로 1274','달오름마을','기타체험','난타체험','2021-09-13','2021-10-09',default,'010-2231-2245','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',50,default,'08.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer3','충청남도 청양군 정산면 천장호길 223-35','개랭이마을','생태체험','메기잡기','2021-08-14','2021-10-09',default,'010-2231-2245','https://www.alimi.or.kr/home/a/selectOnestopHome.do','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',40,default,'05.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer1','전라남도 담양군 대덕면 무월길 42','가정마을','만들기체험','기체조','2021-09-21','2021-10-27',default,'010-1234-5678','www.cehum.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',65,default,'09.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer2','경상남도 거제시 거제중앙로 1274','알프스마을','전통음식체험','감자캐기','2021-08-11','2021-10-09',default,'010-9899-2123','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',65,default,'11.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer7','전라북도 남원시 인월면 인월서길 42','개랭이마을','만들기체험','제철과일 수확','2021-09-27','2021-12-02',default,'011-9980-1234','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',25,default,'05.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer3','전라남도 순천시 별량면 흑가길 6','고들배기마을','전통문화체험','예절학습','2021-08-14','2021-12-16',default,'010-9899-2123','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',25,default,'04.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer6','전라남도 담양군 대덕면 무월길 42','갓고을마을','생태체험','조개캐기','2021-09-13','2021-11-07',default,'051-1234-2222','https://www.alimi.or.kr/home/a/selectOnestopHome.do','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',55,default,'01.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer6','전라남도 곡성군 고달면 가정마을길 65','알프스마을','바다체험','제철과일 수확','2021-09-01','2021-12-22',default,'010-4532-9554','https://www.cheonan.go.kr/tour.do','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',40,default,'09.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer1','전라남도 곡성군 고달면 가정마을길 65','녹향마을','전통문화체험','기체조','2021-08-21','2021-12-16',default,'010-1234-5678','https://www.alimi.or.kr/home/a/selectOnestopHome.do','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',70,default,'');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer7','충청남도 청양군 정산면 천장호길 223-35','월촌마을','농사체험','전통혼례','2021-09-01','2021-10-08',default,'010-2231-2245','https://www.cheonan.go.kr/tour.do','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',45,default,'07.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer2','충청남도 서천군 마서면 합전길 77','개랭이마을','놀이체험','물놀이','2021-08-21','2021-10-07',default,'010-9899-2123','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',35,default,'07.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer4','경상남도 거제시 거제중앙로 1274','가정마을','생태체험','동굴탐험','2021-08-01','2021-10-09',default,'010-4532-9554','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',35,default,'08.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer3','충청남도 청양군 정산면 천장호길 223-35','도래미마을','기타체험','조개캐기','2021-08-01','2021-11-15',default,'010-2221-3333','www.cehum.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',20,default,'05.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer3','전라남도 담양군 대덕면 무월길 42','모꼬지마을','놀이체험','양목장체험','2021-09-27','2021-11-26',default,'051-1234-2222','http://www.푸르미농촌체험농장.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',20,default,'07.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer2','강원도 정선군 남면 광락로 354','장독대마을','만들기체험','난타체험','2021-08-21','2021-11-07',default,'010-9899-2123','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',55,default,'11.jpg');
insert into tblExp 
    (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) 
    values (seqExp.nextVal,'farmer','강원도 평창군 미탄면 마하길 41-5,녹향','녹향마을','농촌체험','감자캐기','2021-08-11','2021-12-22',default,'010-4532-9554','https://www.cheonan.go.kr/tour.do','녹차향기 그윽한 달 뜨는 마을’ 서정적인 뜻을 담은 강진의 녹향월촌권역은 월남리 외 3개리, 총 9개의 마을이 모여 형성된 농촌 휴양마을입니다. 월출산을 배경으로 두고 있는 마을은 아름다운 자연경관과 함께 다산 정약용 선생 등의 발자취가 남아있는 고장입니다. 
','삼거마을의 유기농 감자밭에서 직접 감자 수확체험을 하고 가져가는 체험입니다.',35,default,'11.jpg');
insert into tblExp 
    (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) 
    values (seqExp.nextVal,'farmer','충청남도 청양군 정산면 천장호길 223-35,장구','장구마을','전통문화체험','예절학습','2021-08-01','2021-10-27',default,'010-9899-2123','www.cehum.com','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',50,default,'07.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer','경기도 양평군 용문면 청용길 13-6,갓고을','갓고을마을','생태체험','숭어잡기','2021-09-01','2021-10-07',default,'010-9822-0909','https://www.cheonan.go.kr/tour.do','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','장구를 배워봅시다. 자진모리장단입니다~!',45,default,'10.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer','경상남도 거제시 거제중앙로 1274,갓고을','갓고을마을','만들기체험','조롱박공예','2021-08-14','2021-10-09',default,'011-9980-1234','https://www.cheonan.go.kr/tour.do','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','상세설명',55,default,'12.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer',' 충청남도 청양군 정산면 천장호길 223-35,달오름','달오름마을','기타체험','동굴탐험','2021-09-27','2021-10-07',default,'051-1234-2222','','알프스마을에서 직접 키운 조롱박에 각종 꾸미기 도구를 이용하여 전시품, 화분 등을 만들어요.'||chr(13)||chr(10)||'아이들에게는 전통문화체험, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 조롱박을 각종 도구들을 이용해 예쁘게 꾸며보세요!','동굴탐험 진행자의 지도·감독하에 진행되는 동굴탐험을 통하여 자연의 신비로움과 동굴속 생태환경을 경험해 봄으로써 다양하고 종합적인 과학지식을 배워볼수 있으며, 자립심과 모험심을 키워줄 수 있는 좋은 체험프로그램입니다.',35,default,'05.jpg');
insert into tblExp (seq, id, address, town, expInfo, name, startDate, endDate, regDate, tel, site, townDetail, detail, totalPerson, isEnd, image) values (seqExp.nextVal,'farmer','전라남도 순천시 별량면 흑가길 6,장구마을,장구','장구마을','생태체험','메기잡기','2021-08-01','2021-10-09',default,'011-9980-1234','','장구마을입니다! 저희마을은 항상 자연과 함께합니다.','장구마을에서 메기잡기를 경험호바요!'||chr(13)||chr(10)||'아이들에게는 새로운친구들, 어른들에게는 향수를 불러일으켜 고향을 생각나게 하는 생태계의 동물들과 친해져봅시다!',40,default,'08.jpg');
commit;
select * from tblExp;
----------------------- tblExpApply DummyData-------------------------
create sequence seqExpApply;

insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,60,'user1','2021-07-27','2021-10-02',4,default,'신청하겠습니다! 승인부탁드립니다.','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,59,'user1','2021-07-25','2021-09-28',2,default,'신청합니다 감사합니다','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,58,'user1','2021-07-27','2021-09-27',1,default,'해당 체험 신청희망합니다.','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,32,'user1','2021-07-22','2021-09-30',4,default,'신청합니다!감사합니다^^','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,49,'user1','2021-07-30','2021-10-02',2,default,'농촌체험 신청합니다','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,60,'user2','2021-07-27','2021-10-05',2,default,'신청합니다 감사합니다','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,59,'user2','2021-07-23','2021-10-01',5,default,'신청합니다 감사합니다','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,21,'user2','2021-08-03','2021-09-27',2,default,'해당 체험 신청희망합니다.','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,60,'user3','2021-07-25','2021-10-05',8,default,'신청합니다 감사합니다','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,59,'user3','2021-07-30','2021-10-01',8,default,'농촌체험 신청합니다','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,47,'user3','2021-07-27','2021-10-06',7,default,'신청합니다!감사합니다^^','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,44,'user4','2021-07-28','2021-10-04',3,default,'농촌체험 신청합니다',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,24,'user4','2021-07-23','2021-10-05',5,default,'신청하겠습니다! 승인부탁드립니다.',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,42,'user4','2021-07-31','2021-10-04',1,default,'신청합니다!감사합니다^^',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,43,'user5','2021-07-25','2021-10-05',5,default,'신청하겠습니다! 승인부탁드립니다.',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,32,'user5','2021-08-03','2021-09-29',7,default,'신청합니다',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,52,'user5','2021-07-25','2021-09-27',7,default,'신청합니다!감사합니다^^',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,49,'user6','2021-07-30','2021-10-01',5,default,'신청하겠습니다! 승인부탁드립니다.',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,36,'user6','2021-08-04','2021-09-30',5,default,'신청합니다!감사합니다^^',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,5,'user6','2021-07-24','2021-09-29',1,default,'신청하겠습니다! 승인부탁드립니다.',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,18,'user7','2021-07-24','2021-09-29',4,default,'해당 체험 신청희망합니다.',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,19,'user7','2021-08-01','2021-09-27',2,default,'해당 체험 신청희망합니다.',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,21,'user7','2021-08-03','2021-10-03',2,default,'신청합니다',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,28,'user8','2021-08-04','2021-10-03',8,default,'신청합니다',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,60,'user8','2021-07-31','2021-10-02',5,default,'신청합니다!감사합니다^^',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,24,'user8','2021-08-03','2021-10-01',4,default,'해당 체험 신청희망합니다.',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,10,'user9','2021-07-22','2021-10-02',3,default,'신청합니다 감사합니다',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,29,'user10','2021-07-26','2021-10-04',4,default,'해당 체험 신청희망합니다.',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,47,'user11','2021-07-30','2021-10-06',7,default,'신청합니다!감사합니다^^',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,54,'user9','2021-07-29','2021-09-27',7,default,'신청하겠습니다! 승인부탁드립니다.',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,49,'user10','2021-07-24','2021-10-02',5,default,'신청하겠습니다! 승인부탁드립니다.',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,32,'user11','2021-07-25','2021-09-30',1,default,'신청합니다',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,40,'user9','2021-07-26','2021-09-30',3,default,'신청합니다',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,13,'user10','2021-07-29','2021-10-03',4,default,'신청합니다',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,1,'user11','2021-07-26','2021-10-03',6,default,'해당 체험 신청희망합니다.',default);
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,55,'user','2021-07-27','2021-10-04',3,default,'신청합니다','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,56,'user','2021-07-25','2021-09-27',8,default,'농촌체험 신청합니다','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,57,'user','2021-07-24','2021-10-02',6,default,'신청하겠습니다! 승인부탁드립니다.','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,58,'user','2021-08-03','2021-10-06',4,default,'신청합니다','y');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,59,'user','2021-07-24','2021-09-28',9,default,'신청합니다 감사합니다','n');
insert into tblExpApply(seq,pseq,id,startDate,endDate,totalPerson,regDate,detail,isPass) values(seqExpApply.nextVal,60,'user','2021-07-24','2021-09-28',9,default,'신청합니다 감사합니다','y');
commit;

select * from  tblExpApply;

----------------------- tblExpReview DummyData-------------------------
create sequence seqExpReview;
--user 58,59번 글 제외하고 
insert into tblExpReview values (seqExpReview.nextVal,55,'user','사장님은 친절하지만 체험은 그냥저냥 입니닿ㅎㅎ',default,4);
insert into tblExpReview values (seqExpReview.nextVal,56,'user','사장님은 친절하지만 체험은 그냥저냥 입니닿ㅎㅎ',default,3);
insert into tblExpReview values (seqExpReview.nextVal,57,'user','슬기로운 농촌생활으로 신청한 체험인데요 너무재미있었습니다. 감사합니다!',default,5);
insert into tblExpReview values (seqExpReview.nextVal,58,'user','사장님은 친절하지만 체험은 그냥저냥 입니닿ㅎㅎ',default,5);
--user1
insert into tblExpReview values (seqExpReview.nextVal,60,'user1','슬기로운 농촌생활으로 신청한 체험인데요 너무재미있었습니다. 감사합니다!',default,5);
insert into tblExpReview values (seqExpReview.nextVal,59,'user1','사장님은 친절하지만 체험은 그냥저냥 입니닿ㅎㅎ',default,3);
insert into tblExpReview values (seqExpReview.nextVal,58,'user1','아이들에게 좋은 추억이 생긴것 같아서 좋네요^^ 감사합니다...',default,3);
insert into tblExpReview values (seqExpReview.nextVal,32,'user1','사장님은 친절하지만 체험은 그냥저냥 입니닿ㅎㅎ',default,5);
--user2
insert into tblExpReview values (seqExpReview.nextVal,60,'user2','사장님은 친절하지만 체험은 그냥저냥 입니닿ㅎㅎ',default,3);
insert into tblExpReview values (seqExpReview.nextVal,59,'user2','별로입니다...불친절하고',default,5);
insert into tblExpReview values (seqExpReview.nextVal,21,'user2','슬기로운 농촌생활으로 신청한 체험인데요 너무재미있었습니다. 감사합니다!',default,5);
--user3
insert into tblExpReview values (seqExpReview.nextVal,60,'user3','사장님이 너무친절하고 좋았습니다!~다음휴가때 한번더 오고싶습니다!',default,4);
insert into tblExpReview values (seqExpReview.nextVal,59,'user3','별로입니다...불친절하고',default,2);
insert into tblExpReview values (seqExpReview.nextVal,47,'user3','그냥저냥 그랬습니다.',default,5);
commit;

select * from  tblExpReview;