insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Leucodontaceae', 45);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '안녕하세요 관리자입니다.', 'Crassulaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Scrophulariaceae', 12);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여러분 모두 행복하세요^^.', 'Rosaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '안녕하세요 관리자입니다.', 'Fabaceae', 12);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Pottiaceae', 70);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '여러분 모두 행복하세요^^.', 'Asteraceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여러분 모두 행복하세요^^.', 'Lamiaceae', 77);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Thelotremataceae', 345);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여러분 모두 행복하세요^^.', 'Euphorbiaceae', 70);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여러분 모두 행복하세요^^.', 'Ranunculaceae', 345);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '안녕하세요 관리자입니다.', 'Nephromataceae', 585);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Sphagnaceae', 45);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '안녕하세요 관리자입니다.', 'Polygonaceae', 1);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '안녕하세요 관리자입니다.', 'Polygonaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여러분 모두 행복하세요^^.', 'Brassicaceae', 585);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '안녕하세요 관리자입니다.', 'Pertusariaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Cyperaceae', 585);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여러분 모두 행복하세요^^.', 'Rosaceae', 345);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Polygonaceae', 23);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Capparaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Arthoniaceae', 45);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '안녕하세요 관리자입니다.', 'Liliaceae', 77);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Typhaceae', 70);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '안녕하세요 관리자입니다.', 'Apiaceae', 77);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Asteraceae', 585);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여러분 모두 행복하세요^^.', 'Fabaceae', 1);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Asteraceae', 12);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '안녕하세요 관리자입니다.', 'Rubiaceae', 12);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Fabaceae', 23);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Asteraceae', 70);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여러분 모두 행복하세요^^.', 'Acanthaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여러분 모두 행복하세요^^.', 'Rhizophoraceae', 45);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '안녕하세요 관리자입니다.', 'Viscaceae', 345);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여러분 모두 행복하세요^^.', 'Liliaceae', 345);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '안녕하세요 관리자입니다.', 'Verbenaceae', 12);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여러분 모두 행복하세요^^.', 'Casuarinaceae', 23);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Malvaceae', 345);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Cyperaceae', 1);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Asteraceae', 585);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여러분 모두 행복하세요^^.', 'Mycocaliciaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Ranunculaceae', 70);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Solanaceae', 45);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여러분 모두 행복하세요^^.', 'Oleaceae', 77);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '여러분 모두 행복하세요^^.', 'Orchidaceae', 45);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Boraginaceae', 1);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Loasaceae', 70);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여러분 모두 행복하세요^^.', 'Orchidaceae', 23);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여러분 모두 행복하세요^^.', 'Bruchiaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Coniocybaceae', 77);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Capparaceae', 12);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '안녕하세요 관리자입니다.', 'Asteraceae', 45);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '여러분 모두 행복하세요^^.', 'Asteraceae', 12);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여러분 모두 행복하세요^^.', 'Asteraceae', 585);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Parmeliaceae', 70);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Aquifoliaceae', 77);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '안녕하세요 관리자입니다.', 'Peltulaceae', 345);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '여러분 모두 행복하세요^^.', 'Bryaceae', 12);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '안녕하세요 관리자입니다.', 'Solanaceae', 23);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Fabaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '안녕하세요 관리자입니다.', 'Fabaceae', 345);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Cactaceae', 23);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '안녕하세요 관리자입니다.', 'Urticaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '여러분 모두 행복하세요^^.', 'Scrophulariaceae', 345);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Malvaceae', 585);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Saxifragaceae', 77);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '안녕하세요 관리자입니다.', 'Bryaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '여러분 모두 행복하세요^^.', 'Oedipodiaceae', 77);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '안녕하세요 관리자입니다.', 'Boraginaceae', 77);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Euphorbiaceae', 45);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Rosaceae', 1);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Boraginaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '여러분 모두 행복하세요^^.', 'Pteridaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Urticaceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '안녕하세요 관리자입니다.', 'Scrophulariaceae', 23);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Sphaerophoraceae', 70);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여러분 모두 행복하세요^^.', 'Asteraceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Bromeliaceae', 12);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '안녕하세요 관리자입니다.', 'Turneraceae', 77);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Bacidiaceae', 45);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Apiaceae', 1);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Asteraceae', 70);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여러분 모두 행복하세요^^.', 'Asteraceae', 23);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Poaceae', 585);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Fabaceae', 12);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Apiaceae', 70);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여러분 모두 행복하세요^^.', 'Fabaceae', 45);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '안녕하세요 관리자입니다.', 'Poaceae', 12);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Gunneraceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Piperaceae', 1);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Rosaceae', 1);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Araceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Poaceae', 45);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '공지사항', '날씨가 많이 덥습니다. 건강 주의하세요.', 'Asteraceae', 65);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '이벤트', '안녕하세요 관리자입니다.', 'Scrophulariaceae', 12);
insert into tblNotice (seq, id, category, title, detail, cnt) values (seqNotice.NextVal, 'admin', '지역행사', '여기는 슬기로운 농촌생활 알림마당입니다. 감사합니다^^.', 'Asteraceae', 585);

commit;
