-- tblCommunity 데이터

insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Oleaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농작물 직거래', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Orchidaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '주말농장', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Scrophulariaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농작물 직거래', '날씨 진짜 덥네요!!!', 'Fagaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농촌체험', '날씨 진짜 덥네요!!!', 'Anthocerotaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농작물 직거래', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Scrophulariaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Teloschistaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '주말농장', '안녕하세요~~~', 'Cyperaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Caryophyllaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농작물 직거래', '안녕하세요~~~', 'Scrophulariaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농작물 직거래', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Iridaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Cyperaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Scrophulariaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '일손돕기', '날씨 진짜 덥네요!!!', 'Asteraceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농작물 직거래', '날씨 진짜 덥네요!!!', 'Gesneriaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Brassicaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '주말농장', '날씨 진짜 덥네요!!!', 'Brassicaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '주말농장', '날씨 진짜 덥네요!!!', 'Cyperaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농작물 직거래', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Asclepiadaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Ranunculaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '일손돕기', '날씨 진짜 덥네요!!!', 'Cladoniaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Fabaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '주말농장', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Scrophulariaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '주말농장', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Rubiaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '일손돕기', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Solanaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농작물 직거래', '날씨 진짜 덥네요!!!', 'Lamiaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Euphorbiaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '주말농장', '날씨 진짜 덥네요!!!', 'Poaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농촌체험', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Oxalidaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농작물 직거래', '안녕하세요~~~', 'Hydrophyllaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '주말농장', '날씨 진짜 덥네요!!!', 'Polygalaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농촌체험', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Verrucariaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Amaranthaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농작물 직거래', '날씨 진짜 덥네요!!!', 'Clusiaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Liliaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '주말농장', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Onagraceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Rosaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농작물 직거래', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Ranunculaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농촌체험', '날씨 진짜 덥네요!!!', 'Fabaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '일손돕기', '안녕하세요~~~', 'Poaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '주말농장', '안녕하세요~~~', 'Asteraceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Asteraceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Rosaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '주말농장', '안녕하세요~~~', 'Apiaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '일손돕기', '안녕하세요~~~', 'Rosaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Lauraceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Poaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '주말농장', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Caryophyllaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농촌체험', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Rhamnaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Euphorbiaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농촌체험', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Poaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '주말농장', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Gnetaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농작물 직거래', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Asteraceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농작물 직거래', '안녕하세요~~~', 'Salicaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '주말농장', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Scrophulariaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '주말농장', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Asteraceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농촌체험', '안녕하세요~~~', 'Juncaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '주말농장', '날씨 진짜 덥네요!!!', 'Verbenaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농작물 직거래', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Saxifragaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '일손돕기', '날씨 진짜 덥네요!!!', 'Gesneriaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '일손돕기', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Brassicaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '농촌체험', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Salicaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Parmeliaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Fabaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '일손돕기', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Brassicaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '주말농장', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Orchidaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '일손돕기', '날씨 진짜 덥네요!!!', 'Funariaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농작물 직거래', '날씨 진짜 덥네요!!!', 'Liliaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '일손돕기', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Brassicaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농작물 직거래', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Physciaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농작물 직거래', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Caryophyllaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농촌체험', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Hypnaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '주말농장', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Asteraceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Polygalaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '주말농장', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Leskeaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '일손돕기', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Boraginaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '일손돕기', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Cyperaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Lamiaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농촌체험', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Cactaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '주말농장', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Fabaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '주말농장', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Poaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Liliaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농작물 직거래', '날씨 진짜 덥네요!!!', 'Polemoniaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농촌체험', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Lamiaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Asteraceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Fabaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '주말농장', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Poaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '일손돕기', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Verbenaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '일손돕기', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Physciaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Polemoniaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '주말농장', '안녕하세요~~~', 'Rosaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Linaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농작물 직거래', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Poaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Fabaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농촌체험', '안녕하세요~~~', 'Buxaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Fabaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '주말농장', '안녕하세요~~~', 'Polygalaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Physciaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '주말농장', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Solanaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Pertusariaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '일손돕기', '안녕하세요~~~', 'Oleaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농촌체험', '안녕하세요~~~', 'Rubiaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '일손돕기', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Boraginaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '주말농장', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Scrophulariaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농촌체험', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Polemoniaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농촌체험', '날씨 진짜 덥네요!!!', 'Orchidaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농작물 직거래', '날씨 진짜 덥네요!!!', 'Poaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Violaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농촌체험', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Violaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농촌체험', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Graphidaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '일손돕기', '날씨 진짜 덥네요!!!', 'Polygonaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Scrophulariaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Pinaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농촌체험', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Ericaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농촌체험', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Fabaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농작물 직거래', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Rosaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Poaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '날씨 진짜 덥네요!!!', 'Melastomataceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Marattiaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농작물 직거래', '안녕하세요~~~', 'Graphidaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '주말농장', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Chenopodiaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Boraginaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Polygonaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '일손돕기', '안녕하세요~~~', 'Nymphaeaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농촌체험', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Liliaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '주말농장', '날씨 진짜 덥네요!!!', 'Polygonaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '일손돕기', '안녕하세요~~~', 'Hymeneliaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '주말농장', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Orchidaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '농작물 직거래', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Berberidaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농촌체험', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Polypodiaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '일손돕기', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Portulacaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농촌체험', '날씨 진짜 덥네요!!!', 'Convolvulaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '일손돕기', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Pottiaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Fabaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Asteraceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '주말농장', '날씨 진짜 덥네요!!!', 'Arecaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '주말농장', '날씨 진짜 덥네요!!!', 'Urticaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농촌체험', '날씨 진짜 덥네요!!!', 'Hymenophyllaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '날씨 진짜 덥네요!!!', 'Cyatheaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '일손돕기', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Polygonaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농촌체험', '날씨 진짜 덥네요!!!', 'Asteraceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농작물 직거래', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Polemoniaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농촌체험', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Chrysobalanaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '일손돕기', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Asteraceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '주말농장', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Parmeliaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '주말농장', '날씨 진짜 덥네요!!!', 'Schaereriaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '농촌체험', '안녕하세요~~~', 'Asteraceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '농작물 직거래', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Fabaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '농작물 직거래', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Asteraceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농작물 직거래', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Rutaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '일손돕기', '안녕하세요~~~', 'Scrophulariaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농작물 직거래', '안녕하세요~~~', 'Poaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농작물 직거래', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Asteraceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '농작물 직거래', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Lichinaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Poaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '주말농장', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Orchidaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농촌체험', '날씨 진짜 덥네요!!!', 'Brassicaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '주말농장', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Asteraceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농촌체험', '날씨 진짜 덥네요!!!', 'Rosaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '주말농장', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Gesneriaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농작물 직거래', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Lecideaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농촌체험', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Scrophulariaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '주말농장', '날씨 진짜 덥네요!!!', 'Ranunculaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '농작물 직거래', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Rosaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '일손돕기', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Gentianaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Euphorbiaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농작물 직거래', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Orchidaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농촌체험', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Lamiaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '주말농장', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Brassicaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '농촌체험', '안녕하세요~~~', 'Parmeliaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Calymperaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '일손돕기', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Anacardiaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '주말농장', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Lamiaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농작물 직거래', '안녕하세요~~~', 'Violaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '일손돕기', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Bryaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Lichenotheliaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '주말농장', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Apiaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농작물 직거래', '안녕하세요~~~', 'Nyctaginaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Asteraceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Poaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농촌체험', '안녕하세요~~~', 'Cupressaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Euphorbiaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '주말농장', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Grimmiaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농촌체험', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Poaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '주말농장', '날씨 진짜 덥네요!!!', 'Chenopodiaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농작물 직거래', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Asteraceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Crossosomataceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '주말농장', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Seligeriaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Brassicaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Fabaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '일손돕기', '날씨 진짜 덥네요!!!', 'Acanthaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Graphidaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농작물 직거래', '안녕하세요~~~', 'Pottiaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Brassicaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '주말농장', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Teloschistaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '일손돕기', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Bignoniaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농촌체험', '날씨 진짜 덥네요!!!', 'Cactaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '주말농장', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Euphorbiaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농작물 직거래', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Caprifoliaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농촌체험', '안녕하세요~~~', 'Rubiaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '주말농장', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Ranunculaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농작물 직거래', '안녕하세요~~~', 'Asteraceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Pinaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Pottiaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '일손돕기', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Brassicaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '주말농장', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Polemoniaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '일손돕기', '안녕하세요~~~', 'Asteraceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농작물 직거래', '안녕하세요~~~', 'Fabaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '일손돕기', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Scrophulariaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '주말농장', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Loasaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '농작물 직거래', '날씨 진짜 덥네요!!!', 'Poaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농작물 직거래', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Fabaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '주말농장', '날씨 진짜 덥네요!!!', 'Asclepiadaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Lichinaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '일손돕기', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Megalosporaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '주말농장', '안녕하세요~~~', 'Cyperaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농촌체험', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Rosaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Caliciaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '주말농장', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Sapindaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농작물 직거래', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Salicaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Caryophyllaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '주말농장', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Capparaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '주말농장', '날씨 진짜 덥네요!!!', 'Fabaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '주말농장', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Cyperaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '일손돕기', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Dicranaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Rubiaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Cabombaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Fabaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Gesneriaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농작물 직거래', '안녕하세요~~~', 'Campanulaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '주말농장', '안녕하세요~~~', 'Asteraceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농촌체험', '날씨 진짜 덥네요!!!', 'Cucurbitaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '일손돕기', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Polygonaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '주말농장', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Cactaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '농촌체험', '날씨 진짜 덥네요!!!', 'Asteraceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농촌체험', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Lamiaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '일손돕기', '날씨 진짜 덥네요!!!', 'Euphorbiaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농작물 직거래', '안녕하세요~~~', 'Fabaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Fabaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '날씨 진짜 덥네요!!!', 'Fabaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Hypnaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농작물 직거래', '안녕하세요~~~', 'Asteraceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '일손돕기', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Liliaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '농작물 직거래', '안녕하세요~~~', 'Chenopodiaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농작물 직거래', '날씨 진짜 덥네요!!!', 'Polemoniaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농작물 직거래', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Asteraceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농작물 직거래', '날씨 진짜 덥네요!!!', 'Cyperaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농작물 직거래', '날씨 진짜 덥네요!!!', 'Scrophulariaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '주말농장', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Asteraceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '농촌체험', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Poaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '주말농장', '안녕하세요~~~', 'Onagraceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '일손돕기', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Apocynaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '주말농장', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Scrophulariaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Berberidaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농작물 직거래', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Dicranaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농촌체험', '날씨 진짜 덥네요!!!', 'Myrtaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Scrophulariaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '주말농장', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Catillariaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농작물 직거래', '안녕하세요~~~', 'Grammitidaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농촌체험', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Poaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '일손돕기', '안녕하세요~~~', 'Asteraceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농작물 직거래', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Portulacaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농작물 직거래', '날씨 진짜 덥네요!!!', 'Ranunculaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '주말농장', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Rosaceae', 70);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '일손돕기', '안녕하세요~~~', 'Cyperaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농작물 직거래', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Poaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '농촌체험', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Aizoaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Bombacaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농촌체험', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Papaveraceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '일손돕기', '날씨 진짜 덥네요!!!', 'Myrtaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '농작물 직거래', '날씨 진짜 덥네요!!!', 'Orchidaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '주말농장', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Limnanthaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농촌체험', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Fabaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농작물 직거래', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Oleaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '일손돕기', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Lichinaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user3', '일손돕기', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Brassicaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농작물 직거래', '코로나가 점점 더 심해지는거 같아요ㅠㅠ', 'Piperaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '주말농장', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Trapeliaceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user9', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Teloschistaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '일손돕기', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Fuscideaceae', 585);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '일손돕기', '안녕하세요~~~', 'Poaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '농촌체험', '날씨 진짜 덥네요!!!', 'Onagraceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user4', '농촌체험', '날씨 진짜 덥네요!!!', 'Brassicaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '일손돕기', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Entodontaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user6', '농촌체험', '안녕하세요~~~', 'Fabaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '주말농장', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Aspleniaceae', 65);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농작물 직거래', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Poaceae', 1);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user2', '농작물 직거래', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Asteraceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user5', '농작물 직거래', '안녕하세요~~~', 'Scrophulariaceae', 12);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '주말농장', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Peltigeraceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Gesneriaceae', 23);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user1', '농촌체험', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Campanulaceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '농작물 직거래', '요즘 키우기 좋은 농작물이 뭐가 있을까요?', 'Asteraceae', 45);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user8', '주말농장', '날씨가 많이 덥지만 화이팅 하세요~~!', 'Asteraceae', 345);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user7', '농촌체험', '안녕하세요~~~', 'Rosaceae', 77);
insert into tblCommunity (seq, id, category, title, detail, cnt) values (seqCom.NextVal, 'user', '농작물 직거래', '이번 주말에는 제 농장에 한번 놀러오세요!!', 'Geraniaceae', 70);


commit;